### PR TITLE
Update Main.java

### PR DESCRIPTION
**Pull request by pinguo-liuhongwei**
fixed: The invalid import of PluginProtos caused compile errors

### CODE REVIEW

**Comment by pinguo-liuhongwei** [comment]
PROTOBUF_VERSION=2.6.1

**Comment by Atry** [comment]
Could you please update the build script as well?

**Comment by mroohian** [comment]
hi, is it also possible to compile against v3 of protobuf with this fix?

**Comment by pm-nsimic** [comment]
I get this error when i try to compile with 2.6.1:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/Extension

**Comment by Atry** [comment]
Sorry but I don't the purpose of your guys?

Isn't the published binary of this plugin works with protoc 2.6.x ?

**Comment by johndpope** [comment]
probably best to include a Gemfile with hardcoded protoc version


**Gemfile**
source 'https://rubygems.org'
gem "protobuf", "2.6.1"

**Ruby Version Manager**
curl -sSL https://get.rvm.io | bash    
rvm install ruby-2.2.3   
gem install rvm  (restart terminal)      
gem install bundler  
bundle install  
bundle exec pod install  

then use 
bundle exec protoc --plugin=protoc-gen-as3=path/to/protoc-gen-as3[.bat]--as3_out=output-path your.proto
(which will use older version of protoc)
